---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-latex.tex
geometry: margin=.7in

title: "Resume (1 Page)"
author: "Cory K Costello"

fontawesome: yes
email: "ccostell@uoregon.edu"
github: "coryc3133"
twitter: "@costellock"
web: "costello.netlify.com"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---

# Relevant skills

- **Programming Languages:** 
  - Expertise in R (incl. tidyverse, ggplot2, lme4, lavaan, caret) and Markdown. 
  - Proficiency in Git and Python. 
  - Experience with SQL, HTML, CSS.
- **Data Science:** 
  - Expertise in creating pipelines for cleaning, tidying, reshaping, visualizing, and reporting data.
  - Proficiency in webscraping & accessing data from APIs.
  - Experience working with large, complex datasets.
- **Statistical Modelling:** 
  - Expertise in Linear and Logistic Regression, Longitudinal Data Analysis, MLM/HLM, SEM, Supervised and Unsupervised Machine Learning Techniques, and Social Network Analysis.
  - Proficiency in Automated Text Analysis & Natural Language Processing.
  - Experience with Deep Learning with Keras.
- **Research Approaches** Expertise in experimental, quasi-experimental, survey-based, and data scientific methods. Causal inference in experimental and non-experimental designs.
- **Managing** several simultaneous projects and supervising small teams of research assistants.   

# Experience 

**Graduate Employee** \hfill   2014 - Present  
*University of Oregon, Eugene, OR*

- Teaching Fellow, various roles, including instructing Graduate Statistics and our *R Bootcamp* for incoming graduate students. Teaching responsibilities include explaining advanced topics in statistics and statistical programming to students with different levels of expertise.
- Graduate Research Fellow on NIH & NSF funded projects investigating mental health, personality, and reputation in Online Social Networks. Combines experimental, survey-based, and data scientific methods to uncover how psychological characteristics are reflected in digital footprints.

**Graduate Research assistant** \hfill 2012 - 2014  
*Wake Forest Univeristy, Winston-Salem, NC*

- Responsibilities included experience cleaning and analyzing data, designing research materials, and communicating findings.

# Education

**Ph.D. Psychology** \hfill 2020 (expected)  
*Univeristy of Oregon*


**M.A. Psychology** \hfill 2014  
*Wake Forest University*   

**B.A. Psychology** \hfill 2012  
*New College of Florida (The Honors College of Florida)*    

\centering 


[*see 5-page CV for more detail*](https://costello.netlify.com/#cv)