---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-latex.tex
geometry: margin=.7in

title: "CV"
author: "Cory K Costello"

fontawesome: yes
email: "ccostell@uoregon.edu"
github: "coryc3133"
twitter: "@costellock"
phone: "+1 941 518 9072"
web: "costello.netlify.com"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---


# Professional Appointments 

**Graduate Employee** \hfill   2014 - Present  
*University of Oregon, Eugene, OR*

- Teaching Fellow, various roles (see Teaching Experience).
- Research Fellow, *Big Data, Mental Health, and Personality on Twitter*, NIH (PI: Sanjay Srivastava).
- Research Fellow, *Interpersonal Perception on Twitter*, NSF (PI: Sanjay Srivastava)

**Graduate Research Assistant** \hfill 2012 - 2014  
*Wake Forest Univeristy, Winston-Salem, NC*

- *ACES*, IARPA (Supervisor: Eric Stone)
- *The Character Project*, John Templeton Foundation (PIs: R Michael Furr, William Fleeson)

**Teaching Assistant** \hfill Spring 2012     
*New College of Florida, Sarasota, FL*

**Research Assistant** \hfill 2010-2011     
*Instituional Research & Assesment, New College of Florida, Sarasota, FL*

# Education

**Ph.D. Psychology** \hfill 2020 (expected)  
*Univeristy of Oregon*

- Dissertation Committee: Sanjay Srivastava (Chair), Rob Chavez, Nick Allen, & Ryan Light.
- Dissertation: Human and Computerized Personality Inferences from Digital Footprints on Twitter.

**M.A. Psychology** \hfill 2014  
*Wake Forest University*

- Thesis Committee: Dustin Wood (Chair), R. Michael Furr, Lara Kammrath.
- Thesis: Does the Motive Matter? The Role of Intended Effects in Characterizing Actions and Inferring Personality Traits.

**B.A. Psychology** \hfill 2012  
*New College of Florida (The Honors College of Florida)*

- Thesis Committe: Steven Graham (Chair), Michelle Barton, Maribeth Clark
- Thesis: The Effects of Attachment Priming on Anxiety Sensitivity and Drinking Motives.

# Professional memberships
- Society for Personality and Social Psychology
- Association for Research on Personality
- Society for the Improvement of Psychological Science

# Publications
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent

Thalmayer, A. G., Saucier, G., Srivastava, S., Flournoy, J. C., **Costello, C. K.** (2019). Ethics-Relevant Values in Adulthood: Longitudinal Findings from the Life and Time Study. *In Press at Journal of Personality.* https://doi.org/10.1111/jopy.12462

**Costello, C. K.**, Wood, D., & Tov, W. (2018). Examining East-West Personality Differences Indirectly Through Action Scenarios. *Journal of Cross-Cultural Psychology*, 49, 554-596. https://doi.org/10.1177/0022022118757914 

Wood, D., Tov, W., & **Costello, C. K.** (2015). What a ____ Thing to Do! Formally Characterizing Actions by their Expected Effects, *Journal of Personality and Social Psychology*, 108, 953-976. http://dx.doi.org/10.1037/pspp0000030

# Preprints & Works in Progress (incl. under review)

**Costello, C. K.**, Srivastava, S., Rejaie, R, & Zalewski, M. (2019). *Do the Accounts We Follow Reflect How We Feel? Predicting Individual Differences in Mental Health from Twitter Friends.* Stage 1 RR in principle acceptance at Collabra: Psychology. Preprint available at https://costello.netlify.com/files/MHTwitterFriends_S1RR_revision1.pdf

**Costello, C. K.** & Srivastava, S. (2019). *Perceiving Personality Through the Grapevine: A Network Approach to Reputations.* Revise and Resubmit at Journal of Personality and Social Psychology. Preprint available at https://costello.netlify.com/files/Perceiving_personality_through_grapevine_08.09.2019.pdf.

Hughes, B. T., **Costello, C. K.**, Pearman, J., Razavi, P., Bedford-Petersen, C., Ludwig, R. M., Srivastava, S. (2019). *The Big Five Across Socioeconomic Status: Measurement Invariance, Relationships, and Age Trends.* Stage 1 RR in principle acceptance at at Collabra: Psychology.

Stone, E. R., Luu, j., **Costello, C. K.** (2019). *Automated Calibration Training for Forecasters.* Revise and Resubmit at Journal of Behavioral Decision Making.

**Costello, C. K.**, Srivastava, S., & Saucier, G. (2017). *Stability and Mean-Level Change in the Big Six: A Novel Test of the Maturity and Cumulative Continuity Principles.* Preprint available at https://psyarxiv.com/b36tv/

# Conference Presentations (supervisees in *italics*)

**Costello, C. K.** & Srivastava S. (2019). Do You Feel Like Who You Follow? A Network Approach to Predicting Individual Differences in Mental Health on Twitter. In **Costello, C. K.** & Srivastava S. (Chairs), *The Difference Engine: Advancing Personality Science With Digital Records of Language, Networks, and Behavior.* Symposium conducted 2019 Biennial Meeting of the Association for Research in Personality (Grand Rapids, MI.)

**Costello, C. K.** & Srivastava, S. (2019). Longitudinal stability and change in the Big Six. In G. Saucier & S. Srivastava (Chairs), *Longitudinal Stability/Change in Personality Understood Broadly: Beyond the Big Five.* Symposium conducted at the 2019 Lifespan Social-Personality  Preconference, part of the 20th annual meeting of the Society of Personality and Social Psychology (Portland, OR).  

**Costello, C. K.** & Srivastava, S. (2018). Consensus, Accuracy, and Consequences of Hearsay Reputations. In R. Rau (Chair), *Making good impressions: On the antecedents and consequences of peer reputations.* Symposium conducted at the 19th European Conference on Personality (Zadar, Croatia).    

*Xu, C.*, **Costello, C. K.**, & Srivastava, S. (2018). *What did you say she was like? Features of Gossip Associated with Hearsay Accuracy and Consensus.* Poster presented at the 19th annual meeting of the Society of Personality and Social Psychology (Atlanta, GA).    

**Costello, C. K.** & Srivastava S. (2017). Perceiving through the Grapevine. In **C. K. Costello** & S. Srivastava (Chairs), *What Do We Do with Interpersonal Knowledge? Social Functions of Interpersonal Perception, Gossip, & Reputation.* Symposium conducted at 2017 Biennial Meeting of the Association for Research in Personality (Sacramento, CA).     

**Costello, C. K.** & Srivastava, S. (2017). *Perceiving through the Grapevine: Consensus and Accuracy of Hearsay Reputations.* Poster presented at the 18th annual meeting of the Society for Personality and Social Psychology (San Antonio, TX).    

**Costello, C. K.** & Srivastava, S. (2016). *Traits, What Are They Good For? Functions and Affordances of Perceiving Big Five Personality Attributes.* Poster presented at the 17th annual meeting of the Society for Personality and Social Psychology (San Diego, CA).    

**Costello, C. K.** & Wood, D. (2015). *Does the Motive Matter? The Role of Intended Effects in Characterizing Actions and Inferring Personality Traits.* Poster presented at the 16th annual meeting of the Society for Personality and Social Psychology (Long Beach, CA).    

Wood, D., Tov, W. & **Costello, C. K.** (2015). *The strange inversion: Defining Big Five-relevant action descriptors simultaneously identifies important situational features.* Paper presented at the International Convention of Psychological Science (Amsterdam, Netherlands).    

Wood, D., **Costello, C. K.**, & Tov, W. (2015). *Are we talking about the same thing here? Cross-cultural differences in the meaning of trait concepts.* Paper presented at the International Convention of Psychological Science (Amsterdam, Netherlands).    

Wood, D., Tov, W., & **Costello, C. K.** (2014). Examining East-West Personality Differences Indirectly Through Action Scenarios. In G. Saucier (Chair), *Response profiles as indicators of cultural models, internalization, and normativity.* Symposium conducted at the 22nd annual congress of the International Association of Cross-Cultural Psychology (Reims, France).   

**Costello, C. K.**, Wood, D., & Tov, W. (2014). *Actions are What They Do: Identifying Trait-Relevance through Action Effects.* Poster presented at the 15th annual meeting of the Society for Personality and Social Psychology (Austin, TX).    

Anderson, R. A., **Costello, C. K.**, Helzer, E. G., Furr, R. M., & Fleeson, W. (2014). *Individual and situational predictors of helping: Results from a 10-week longitudinal study.* Talk presented at the Morality and Justice Preconference held at the annual meeting of the Society for Personality and Social Psychology (Austin, TX).     

**Costello, C. K.** & Wood, D. (2013) *It's the Thought That Counts: The Differential Role of Intended and Unintended Effects in Characterizing Actions.* Poster presented at the 35th annual meeting of the Society of Southeastern Social psychologists (Augusta, GA).

# Technical skills

- **Programming Languages:** 
  - Expertise in R (incl. tidyverse, ggplot2, lme4, lavaan, caret) and Markdown. 
  - Proficiency in Git and Python. 
  - Experience with SQL, HTML, CSS.
- **Data Science:** 
  - Expertise in creating pipelines for cleaning, tidying, reshaping, visualizing, and reporting data.
  - Proficiency in webscraping & accessing data from APIs.
  - Experience working with large, complex datasets.
- **Statistical Modelling:** 
  - Expertise in Linear and Logistic Regression, Longitudinal Data Analysis, MLM/HLM, SEM, Supervised and Unsupervised Machine Learning Techniques, and Social Network Analysis.
  - Proficiency in Automated Text Analysis & Natural Language Processing.
  - Experience with Deep Learning with Keras.
- **Research Approaches:** Expertise in experimental, quasi-experimental, survey-based, and data scientific methods. Causal inference in experimental and non-experimental designs.

# Honors & Awards
\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{8pt}
\noindent
Special Opportunities Travel Award, University of Oregon, Eugene, OR. \hfill Spring 2018   
Tuition Scholarship, Wake Forest University, Winston-Salem, NC. \hfill 2012-2014    
Summer Research Funding, Wake Forest University, Winston-Salem, NC \hfill Summer 2013     
Alumni Association Grant, New College of Florida, Sarasota, FL. \hfill 2010-2011    
New College Academic Scholarship, New College of Florida, Sarasota, FL. \hfill 2008-2012       
Florida Bright Futures Scholarship, New College of Florida, Sarasota, FL. \hfill 2008-2012     
First Generation College Student Grant, New College of Florida, Sarasota, FL. \hfill 2008-2012     

# Teaching Experience
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent

## University of Oregon

Data Analysis I \hfill Fall, 2015, 2017    
 - Lab Instructor.    
 - Graduate Level Course covering univariate statistics. Basic Logic of Frequentist Statistics, NHST, comparing means (*t* tests & ANOVA), and correlation.    
 - Instruction included reviewing materials from lecture & analyzing data in R. Created Lab Materials (in R/Rmarkdown) walking through data analysis in R.

Data Analysis II \hfill Winter, 2016, 2019, 2020   
 - Lab Instructor.    
 - Graduate Level Course covering basic multivariate statistics. More advanced regression models, complex designs (repeated measures, nested designs, etc.), and continuous and factorial interactions.    
 - Instruction included reviewing materials from lecture & analyzing data in R. Created Lab Materials (in R/Rmarkdown) walking through data analysis in R.     
 
Data Analysis III \hfill Spring, 2016, 2019   
 - Lab Instructor.    
 - Graduate Level Course covering advanced multivariate stastics. Multi-level modelling, Structural Equation Modelling, and other advanced data analytic techniques.    
 - Instruction included reviewing materials from lecture & analyzing data in R. Created Lab Materials (in R/Rmarkdown) walking through data analysis in R. Provided several guest lectures.   

Personality \hfill Spring, 2019  
 - Teaching Assistant   
 - Broad survey on personality science for mid-level undergraduates.    
 - Primarily graded assignments. Delivered guest lecture on personality and culture.
 
Personality \hfill Summer, 2015    
 - Co-Instructor    
- Upper-level undergraduate course on personality science, covering personality assesment, development, interpersonal perception, and the person-situation debate.    
 - Designed course, prepared lectures and assignments, and graded assignments.    
 
Thinking \hfill Fall, 2014; Spring, 2015    
 - Teaching Assistant     
 - Survey on cognitive psychology and its applications.    
 - Prepared assignments, graded assignments, maintained online course materials.    
 
Psychology & Law \hfill Winter, 2015    
 - Teaching Assistant     
 - Survey on psychology's application to the legal system.    
 - Graded assignments and maintained online course materials.   
 
## New College of Florida

Social Science Research Lab \hfill Spring, 2012     
 - Walk in tutor-service    
 - Assisted students completing undergraduate theses and other avanced projects with planning and executing data analysis (using SAS).    

Lab in Social/Personality Psychology \hfill Sping, 2012    
 - Teaching Assistant   
 - Undergraduate-level course on research methods and data analysis in social-personality psychology.
 - Assisted with students' research projects (including data analysis) and course administration.

# Students Mentored

Xu, Chenle. *Psychology Honors Student*, University of Oregon. \hfill A/Y 2016-2017    
- Honor's thesis: *What did you say she was like? Features of gossip associated with hearsay accuracy and consensus.*    
- Currently earning PhD in Clinical Psychologt at University of North Texas

Davis, K. *McNair Scholar*, University of Oregon. \hfill A/Y 2018-2019    
- McNair Project: *Heard it Through the Grapevine: Does Physical Attractiveness Affect
Impressions Formed via Gossip?*

# Service
\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{8pt}
\noindent
Facilitator, Quantitative Methods Lab (Dept Brown Bag), *University of Oregon.* \hfill Sping, 2018    
Facilitator, Data Science Club (formerly called R Club), *University of Oregon.* \hfill 2016-2018    
Lab Ambassador, Regional Intel Science Fair, *University of Oregon.* \hfill Spring 2017    
Student Organizer, Seminar in Self-Regulation (Dept Brown Bag), *Wake Forest University.* \hfill 2013-2014    